### ISSUE TITLE
Background dimmed view is NOT animating

### ISSUE THREAD

**Issue by omidgolparvar** [huri000/SwiftEntryKit#132]
**Describe the bug**
In the previous versions, dimmed background view (screenBackground) was dismissed animatedly (fade out). But in this version, after dismissing our UIView/UIViewController, dimmed view is dismissing WITHOUT animation.

**To Reproduce**
I use this code:

```swift
var attributes = EKAttributes.centerFloat
attributes.entryBackground = .visualEffect(style: .extraLight)
attributes.entranceAnimation = .init(
	translate: nil,
	scale: .init(from: 1.2, to: 1, duration: 0.2),
	fade: .init(from: 0.0, to: 1, duration: 0.2)
)
attributes.displayDuration = .infinity
attributes.shadow = .none
attributes.scroll = .disabled
attributes.entryInteraction = .absorbTouches
attributes.screenInteraction = .absorbTouches
attributes.positionConstraints.maxSize = .init(width: .constant(value: 300), height: .constant(value: 500))
attributes.positionConstraints.verticalOffset = 12
attributes.positionConstraints.size = .init(width: .offset(value: 12), height: .intrinsic)
attributes.roundCorners = .all(radius: 8)
attributes.screenBackground = .color(color: UIColor.black.withAlphaComponent(0.4))
attributes.exitAnimation = .init(
	translate: nil,
	scale: nil,
	fade: .init(from: 1.0, to: 0.0, duration: 0.2)
)

// setting up elements...

let simpleMessage = EKSimpleMessage(image: imageContent, title: titleContent, description: descriptionContent)
let alertMessage = EKAlertMessage(simpleMessage: simpleMessage, imagePosition: .top, buttonBarContent: buttonBarContent)
let contentView = EKAlertMessageView(with: alertMessage)
SwiftEntryKit.display(entry: contentView, using: attributes)
```

**iPhone (please complete the following information):**
 - Device: iPhone 8
 - iOS Version: iOS 12
 - Xcode Version: 10
 - Dependency Manager Version: CocoaPods 1.4.0
 - SwiftEntryKit Release # 0.8.2

**Screenshots / Video Links**
![screenrecording_10-27-2018 14-14-32](https://user-images.githubusercontent.com/5128342/47603591-05ac5980-d9fb-11e8-93ee-8809eaf6e073.gif)

**Comment by huri000** [comment]
@omidgolparvar - Thank you for opening this issue. I'll investigate and keep you posted.

**Comment by huri000** [comment]
Fixed in `0.8.3` - Please let me know if that works for you. :-)

**Comment by omidgolparvar** [comment]
Unfortunately, I still have the issue. :(

**Comment by omidgolparvar** [comment]
Oooooh... 
It seems that the mistake is shared between us!! 😂
I installed `0.8.3`, and you did not release `0.8.4` on Cocoapods.
😁

**Comment by huri000** [comment]
O.K :-)
**0.8.3** already contains the fix that is exemplified by the gif in my previous comment. So, if you installed version **0.8.3** you must have that fix and it should work well. Let me know if I misunderstand something.

**Comment by omidgolparvar** [comment]
I installed `0.8.3` and the problem is still here. 😕

![img_1095](https://user-images.githubusercontent.com/5128342/47606487-f2ac8000-da20-11e8-8225-bf4c7576d2f2.gif)

**Comment by omidgolparvar** [comment]
The problem was cocoapod! When ever I tried to install `0.8.3`, it uses cached version of SwiftEntryKit. I added `skip_download_cache: true` in `~/.cocoapods/config.yaml` in order to force cocoapod to redownload SwiftEntryKit, and the problem is solved.

Thanks.
😋👍
