### ISSUE TITLE
Unable to run the Example Project

### ISSUE THREAD

**Issue by krummler** [huri000/SwiftEntryKit#139]
**Describe the bug**
I tried suggestions found in other 

**To Reproduce**
1. `pod try SwiftEntryKit` and wait for it to open (cloning repo yields same result)
2. Build QuickLayout
3. Build SwiftEntryKitDemo

**Expected behavior**

**Screenshots**
![screenshot 2018-11-16 at 11 33 52](https://user-images.githubusercontent.com/1032307/48616320-88d62500-e993-11e8-96cb-105798cb70ac.png)

**iPhone (please complete the following information):**
 - Any device
 - iOS Version: 12.1
 - Xcode Version 10.1
 - Dependency Manager: Cocoapods 1.6.0.beta.1
 - SwiftEntryKit Release: 0.8.4

**Additional info**
I can get the project to work by:
1. Removing the SwiftEntryKit target from the example workspace
2. Cleaning workspace
3. Rebuild

**Comment by huri000** [comment]
Hi, 
Have you taken a look at the [example project installation](https://github.com/huri000/SwiftEntryKit#example-project-installation) section?
What you described happens when one downloads the project. Instead, you need to:
```bash
$ git clone --recurse-submodules https://github.com/huri000/SwiftEntryKit.git
```
There are multiple issues referring this, which are currently closed because they were resolved.
Please let me know if that works for you.

**Comment by krummler** [comment]
Hi Huri000,

That does work, but it seems kind of redundant? This breaks the `pod try` mechanism and installs dependencies twice: once through the pod dependencies and once manually. 
Simply removing the duplicate build targets also works, which confirms all the needed dependencies are already there.

**Comment by huri000** [comment]
Yes @krummler, you are right. I remember struggling with it quite a bit back when I initially release the library. It had something to do with `SwiftEntryKit` started supporting Carthage and so I had to Include the `QuickLayout` framework as a submodule. Xcode's build tool could not find it in its proper location in the `Carthage/Build/...` path.  After tinkering with it a bit (unsuccessfully) I descide it didn't worth the time and regressed to the `git clone` using `recurse` flag, which do work.

**Comment by avjiang** [comment]
Hi i run the 

  `$ git clone --recurse-submodules https://github.com/huri000/SwiftEntryKit.git`

and i still having the QuickLayout module not found issue. What should I do? 

I wanted to give this library a try :)
